[tasks.qemu]
command = "qemu-system-riscv64"
args = [
    "-M", "virt", 
    "-serial", "mon:stdio", 
    "-bios",  "fw_jump.bin",
    "-kernel", "target/riscv64gc-unknown-none-elf/debug/losgatos",
    "-nographic"
]
dependencies = ["build"]